name: Keploy API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Docker Image
      run: docker build -t taskmanager-backend ./Task-Manager

    - name: Run Backend Container
      run: docker run -d --name taskmanager-app -p 5000:5000 taskmanager-backend

    - name: Install Keploy CLI
  run: |
    curl --silent -L https://keploy.io/ent/install.sh | bash

    - name: Run Keploy Test Suite
      env:
        KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
      run: |
        keploy test-suite \
          --app=d3e8cfb8-27c9-4c5e-be63-2f4a591b92ee \
          --base-path=http://localhost:5000/ \
          --cloud

